### PR TITLE
Aaron

### PR DESCRIPTION
**Pull request by oli-tiger**
Had some issues concerning the branching

### CODE REVIEW

**Review by hir-boar — COMMENTED** [review]
you need to add a gitignore file

**Comment by oli-tiger** [comment]
Added the gitignore file, thought it was still here. Should I make a new commit, or delete the files that are to be ignored?

**Comment by hir-boar** [comment]
> Added the gitignore file, thought it was still here. Should I make a new commit, or delete the files that are to be ignored?

Now to need to remove the files that should be excluded by the gitignore

**Comment by hir-boar** [comment]
> Added the gitignore file, thought it was still here. Should I make a new commit, or delete the files that are to be ignored?

Yes you need to remove the ignored files with an additional commit

**Review by hir-boar — APPROVED** [review]

**Pull request merged**
